# Generated by Django 5.2.4 on 2025-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
    ]
