# Generated by Django 5.2.4 on 2025-11-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_flashcard_known_flashcard_need_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashCard',
            new_name='GenerateFlashCards',
        ),
    ]
