# Generated by Django 5.2.4 on 2025-11-10 06:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_flashcard_generateflashcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=accounts.models.user_document_path),
        ),
    ]
