# Generated by Django 5.2.4 on 2026-07-21 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatequestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
