# Generated by Django 5.2.4 on 2026-07-21 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_chatmessage_suggestions_alter_generatequestion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('highlight', 'Highlight'), ('note', 'Note'), ('ai', 'AI'), ('chat', 'Chat'), ('scratch', 'Scratch')], default='note', max_length=16)),
                ('anchor_start', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor_end', models.PositiveIntegerField(blank=True, null=True)),
                ('quoted_text', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('color', models.CharField(default='vermillion', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.chapter')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_id', 'anchor_start', 'created_at'],
            },
        ),
    ]
