# Generated by Django 5.2.4 on 2026-10-08 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_chatmessage_is_unanswered'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='active_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='ingestion_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='pending_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='version_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'version', 'page_number')},
        ),
        migrations.CreateModel(
            name='DocumentIndexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_versions', to='accounts.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='unique_document_index_version')],
            },
        ),
    ]
